site_name: My Docs
repo_name: Hehongyuanlove/wiki
repo_url: https://github.com/Hehongyuanlove/wiki
theme:
  name: material
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - content.code.copy # 代码复制
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
markdown_extensions:
  - admonition  # 提示块
  - pymdownx.details  # 提示块可折叠
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences